--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Theslowaja/playerstatus
build-by-default: true
branches:
- main
projects:
  playerstatus:
    path: ""
    icon: "d4d38780672812f5aeff503cf4bbe6e4.png"
...
