name: PlayerStatus
main: Theslwaja\PlayerStatus\Main
author: Theslowaja
credits: ShandyR
version: 1.0.0
api: 4.0.0

commands:
  player:
    permission: player.use
    
permissions:
  player.use:
    default: true
